### ISSUE TITLE
My own userscripts

### ISSUE THREAD

**Issue by opencooper** [stephenmk/edrdg-scripts#1]
Thanks for making your scripts public and freely licensed. Incidentally, I also wrote my own userscripts for many of the things you have. Maybe mine can serve as some inspiration for improvements.

Here's what my n-grams results look like:

![Screen Shot 2023-10-27 at 4 06 20 AM](https://github.com/stephenmk/edrdg-scripts/assets/74226537/ba9c78aa-21e3-44e9-8fad-2ddfb022b16b)

Very similar to yours, including adding digit separators. I also have toggling of the percentages, but don't have individual toggles because I just simply remove the kanji I don't want from the input field at the bottom and re-submit. (it's very useful for adding forms as I think of them) I also have sorting, but mine's a drop-down. (don't really sort more than once though) There's a convenience link for performing the same search in the K/M n-grams too. Finally, I include some color coding if the percentage is low enough to qualify as a rare kanji (threshold is probably outdated now), and also if the n-gram count is greater than 1 million, warranting a frequency tag. The "show original" checkbox is just there as a sanity check, in case I messed up some logic. I've [uploaded the code to a Gist](https://gist.github.com/opencooper/a552a187b951fc251bf5e98544b54bb0), if you're curious.

---

I also like what you've done with threading the entries on the submissions page. There's a lot of duplication on the original. One time, I had to catch up on two weeks of edits and I kept seeing the same thing I reviewed on the next day's page. So my approach was to add a collapse button, and keep those entries minimized unless there was a change since then. (only showing the newer ids for a given sequence number) Very simple and uses localStorage to keep track.

![Screen Shot 2023-10-27 at 4 38 36 AM](https://github.com/stephenmk/edrdg-scripts/assets/74226537/ca351b71-783e-413e-bf15-04657a8108b5)

I've also [included this code in a Gist](https://gist.github.com/opencooper/97f7c2056308b55fdef677123bb4f813).

At one point, I wanted to create a "linter" for editing that would take advantage of all the unwritten editorial things I've picked up over the years, because there are so many things to keep in mind while creating an entry. A linter like that used in programming would be useful. But never got around to it.

**Comment by stephenmk** [comment]
Thanks for sharing. I haven't received any feedback regarding most of my scripts, so it's certainly interesting to see how someone else might go about designing improvements to these interfaces.

It's been a over a year since I've made any major changes to these two scripts in particular, so you could say I've grown content the current setup. But there are still improvements that could be made and inconveniences that could be fixed.

> I just simply remove the kanji I don't want from the input field at the bottom and re-submit. (it's very useful for adding forms as I think of them)

Yeah I find myself editing the page URL when I want to add or remove kanji (since the parameters in the URL are just a delimited list of search terms). It might be worthwhile to add a dedicated textbox and button to the result page to handle this instead.

You may have already seen this, but I wrote [another script](https://github.com/stephenmk/edrdg-scripts#n-gram-term-combinations-install ) for expanding formatted strings into a delimited list of search terms.  So for example, `〈巡（り）／めぐり〉〈合／あ〉わせ` would expand into six search terms: `巡合わせ；巡り合わせ；めぐり合わせ；巡あわせ；巡りあわせ；めぐりあわせ`. So a lot of times when I want to redo a search, I'll go back and edit the original formatted string and then expand it again. Currently I have to browse back to the query page to do this, but it would be nice to be able to do this on the search result page as well.

> Finally, I include some color coding if the percentage is low enough to qualify as a rare kanji (threshold is probably outdated now), and also if the n-gram count is greater than 1 million, warranting a frequency tag.

It can be tough to remember all the criteria involved for all of the different metadata tags. Some of them can be highly context dependent. For example, I think it's okay to be very liberal with the [sK] tag in entries for long expressions that list many obvious spelling variations. So I might use the [sK] tag on a term with 30% of the n-gram count total in an expression entry, but not for other types of entries. Converting these sorts of guidelines into criteria that can be checked by a linter sounds very challenging. Anything that helps reduce the large mental overhead required to edit entries is worth considering, though.

> So my approach was to add a collapse button, and keep those entries minimized unless there was a change since then. (only showing the newer ids for a given sequence number) Very simple and uses localStorage to keep track.

My script currently starts with all entries collapsed, but it might make more sense to start expanded and keep track of which IDs the user has collapsed. Older entries within threads could start collapsed regardless of whether they've been seen, since they're mostly just duplicated info.

Thanks again for sharing the code.

**Comment by opencooper** [comment]
I've seen your script that goes through the different possible iterations for surface forms. It's clever. I just have always done these combinations manually when I think of them using copy-paste, but yours is certainly faster and more comprehensive if you know the syntax. I'll give it a try in the future. :)

Yeah, things that are usually down to editorial discretion can be hard to represent in code. Some of the editors are definitely more aggressive with sK, so my color-coding is more as a reminder for the obvious cases.

**Comment by stephenmk** [comment]
I [updated my script](https://github.com/stephenmk/edrdg-scripts/commit/dd5a34c6dc99c6f398b51a1bb9bba5bf064935c9) for collapsible entries so that all entries (except for older entries within threads) are initially expanded. When an entry is collapsed, the script will write to a cookie that the entry ID has been seen.

> but yours is certainly faster and more comprehensive if you know the syntax

I can see how some of the long expressions might make the syntax look intimidating, but I think you can learn it in just a few seconds.

There are only two categories of groups

1. Alternative groups
    - 天{の,之}邪鬼 expands into two terms: 天の邪鬼 and 天之邪鬼
2. Omissible groups, which are just alternative groups with the addition of an empty alternative
    - 天(の,之)邪鬼 expands into three terms: 天の邪鬼, 天之邪鬼 and 天邪鬼

Both types of groups can be nested within either type of group, which is useful when the word contains an optional okurigana.
- {取(り),とり}引き expands into three terms: 取り引き, 取引き, and とり引き. 

The types of braces used to denote the different types of groups [can be easily customized in the script](https://github.com/stephenmk/edrdg-scripts/blob/dd5a34c6dc99c6f398b51a1bb9bba5bf064935c9/ngram_group_parser.user.js#L14-L20) as well.

**Comment by opencooper** [comment]
Yeah, it did look visually daunting, but now that you explain it, the rules are pretty simple. The usage of parentheses for optional okurigana is familiar from the kokugos. I tried as an example `{伊達,だて,ダテ}{眼鏡,めがね,メガネ}`  and it worked as expected. Thanks for the illumination.
