### ISSUE TITLE
[ngram_group_parser] Using browser back button creates duplicate buttons

### ISSUE THREAD

**Issue by razasyedh** [stephenmk/edrdg-scripts#2]
I experienced this in Firefox (Greasemonkey) and was not able to reproduce in Chrome (Tampermonkey), but whenever I hit the back button after viewing n-gram lookup results, the script would run again, adding another "Expand Groups" button.

![Screen Shot 2023-12-06 at 10 59 04 AM](https://github.com/stephenmk/edrdg-scripts/assets/4624760/ca4cfade-a86a-4a91-93e3-f3f09e963b52)

The way I fixed it was in `main()`, after initializing `parseButton`, give it an id:

	parseButton.id = "expandButton";

And adding a check as the first step of `main()`:

	if (document.getElementById("expandButton") != null) {
		return;
	}

If you can reproduce, could add this check.

**Comment by stephenmk** [comment]
I also use Firefox, but I don't experience this issue. I think it's because I use [violentmonkey](https://github.com/violentmonkey/violentmonkey) rather than greasemonkey.

This problem used to affect greasemonkey in chrome, so I used to initialize the scripts differently to avoid it.

```js
// Starting the program this way prevents it from
// running again on return visits to cached pages
// (when running the program via greasemonkey).
window.addEventListener("load", main, false);
```

In mid-February earlier this year [I replaced this method](https://github.com/stephenmk/edrdg-scripts/commit/84f765c62b8d708be21f86d8749a5429eec2fc32) with a simple call to the `main` function. Here's what I wrote in the commit message:

```
Update script initialization method
The `window.addEventListener("load", main, false);` method no longer
seems to be necessary in the latest versions of GreaseMonkey and
ViolentMonkey.
```

I guess I only tested greasemonkey in chrome.

Thanks for letting me know. I think I'll update the script as you suggested.
